name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 195.35.10.198
        username: u488182444.bestsoftguide.com
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: .output/public/
        server-dir: public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
